# Generated by Django 4.2.3 on 2023-09-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_voter_admin'),
        ('account', '0004_remove_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
