# Generated by Django 4.2.3 on 2023-10-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='election',
        ),
        migrations.AddField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.election'),
        ),
    ]
