# Generated by Django 4.2.3 on 2023-10-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
