# Generated by Django 4.2.6 on 2023-10-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
