<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-10-09 04:53
=======
# Generated by Django 4.2.3 on 2023-10-09 06:32
>>>>>>> 6d0d24facd7fcd820678c4caf29f2e8991731aa2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='admin',
            new_name='user',
        ),
    ]
