# Generated by Django 4.2.4 on 2023-10-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='admin',
            new_name='user',
        ),
    ]
