# Generated by Django 4.2.6 on 2023-10-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_voter_election_alter_voter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.election'),
        ),
    ]
