# Generated by Django 4.2.4 on 2023-10-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_election_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='active',
        ),
    ]
