# Generated by Django 4.2.3 on 2023-10-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_voter_election_voter_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
