# Generated by Django 4.2.3 on 2023-10-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_election_is_open'),
        ('api', '0004_alter_voter_election'),
    ]

    operations = [
    ]
