# Generated by Django 4.2.6 on 2023-10-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_0002_election_is_open_0004_alter_voter_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
