# Generated by Django 4.2.3 on 2023-10-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_voter_election'),
        ('api', '0006_alter_election_title'),
    ]

    operations = [
    ]
