# Generated by Django 4.2.3 on 2023-10-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='position',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
