# Generated by Django 4.2.3 on 2023-09-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_rename_votes_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(upload_to='media/candidates'),
        ),
    ]
