# Generated by Django 4.2.4 on 2023-10-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
