# Generated by Django 4.2.3 on 2023-09-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_candidate_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='phone',
        ),
    ]
