# Generated by Django 4.2.4 on 2023-10-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_voter_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(upload_to='candidates'),
        ),
    ]
