# Generated by Django 4.2.4 on 2023-10-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_candidate_photo'),
        ('voting', '0008_alter_candidate_photo'),
    ]

    operations = [
    ]
