# Generated by Django 4.2.4 on 2023-10-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_rename_admin_voter_user'),
        ('voting', '0009_merge_20231006_0000'),
    ]

    operations = [
    ]
